version: "3"
services:
  web:
    # image hosting my inferno instance
    image: fit-web:latest
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
  nodeservice:
    # replace username/repo:tag with your name and image details
    image: fit-gateway-api:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4200:80"
    networks:
      - webnet
networks:
  webnet: